### PR TITLE
Add concurrently to package.json

### LINKED ISSUE #11: Add `both` script to backend Package
[Jillian found](https://codethedream.slack.com/archives/C060LAKRWTG/p1698914060747149) a [useful package](https://github.com/Code-the-Dream-School/ee-prac-team2-front/pull/5#discussion_r1380867841) called `Concurrently` that can easily run both the backend and the frontend apps at the same time and keep the outputs of both: 

Please add a similar `both` command to the backend app.

You'll need to reverse which directory it changes to since it's being called from the other repo's folder this time.

### PR DESCRIPTION
**Pull request by catbus00**
Fixes #11 - Updates made as requested

### CODE REVIEW

**Comment by catbus00** [comment]
Fixes #11 - Updates made as requested

**Comment by dargaCode** [comment]
> Fixes #11 - Updates made as requested

Looks like these Closing  Keywords only work if we put them in the description "comment" but not in any other comments, which is kindof dumb. I updated the description and now it's linked 🙌

**Comment by dargaCode** [comment]
Removed README changes which should be exclusive to PR #6 (see [slack thread)](https://codethedream.slack.com/archives/C060LAKRWTG/p1699122656551589)

**Review by dargaCode — APPROVED** [review]
Working great, thank you so much for finding this!

**Comment by dargaCode** [comment]
Usually the PR author should merge on their own but I'm doing it in this case just to make sure I kept things untangled

**Comment by dargaCode** [comment]
Great job!

**Pull request merged**
